CREATE TABLE pack_category(
  pack_name TEXT NOT NULL,
  category INTEGER NOT NULL,
  file_size INTEGER NOT NULL,
  PRIMARY KEY (pack_name, category)
);
INSERT INTO `pack_category` VALUES (/*pack_name*/"bysg6q", /*category*/6, /*file_size*/9587885);
INSERT INTO `pack_category` VALUES (/*pack_name*/"bysg6q", /*category*/7, /*file_size*/625824);
INSERT INTO `pack_category` VALUES (/*pack_name*/"sgrpqf", /*category*/6, /*file_size*/9488524);
INSERT INTO `pack_category` VALUES (/*pack_name*/"sgrpqf", /*category*/7, /*file_size*/957216);
INSERT INTO `pack_category` VALUES (/*pack_name*/"f9abdj", /*category*/6, /*file_size*/6896376);
INSERT INTO `pack_category` VALUES (/*pack_name*/"f9abdj", /*category*/7, /*file_size*/3311200);
INSERT INTO `pack_category` VALUES (/*pack_name*/"lrkkeh", /*category*/6, /*file_size*/7798941);
INSERT INTO `pack_category` VALUES (/*pack_name*/"lrkkeh", /*category*/7, /*file_size*/719232);
INSERT INTO `pack_category` VALUES (/*pack_name*/"dbqbfl", /*category*/6, /*file_size*/8639692);
INSERT INTO `pack_category` VALUES (/*pack_name*/"dbqbfl", /*category*/7, /*file_size*/690432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"oye5fm", /*category*/6, /*file_size*/5169644);
INSERT INTO `pack_category` VALUES (/*pack_name*/"oye5fm", /*category*/7, /*file_size*/5072608);
INSERT INTO `pack_category` VALUES (/*pack_name*/"zipgrw", /*category*/6, /*file_size*/8701505);
INSERT INTO `pack_category` VALUES (/*pack_name*/"zipgrw", /*category*/7, /*file_size*/1784192);
INSERT INTO `pack_category` VALUES (/*pack_name*/"jgshuj", /*category*/6, /*file_size*/9637821);
INSERT INTO `pack_category` VALUES (/*pack_name*/"jgshuj", /*category*/7, /*file_size*/827744);
INSERT INTO `pack_category` VALUES (/*pack_name*/"m6242n", /*category*/6, /*file_size*/9255959);
INSERT INTO `pack_category` VALUES (/*pack_name*/"m6242n", /*category*/7, /*file_size*/811616);
INSERT INTO `pack_category` VALUES (/*pack_name*/"k3ubkw", /*category*/6, /*file_size*/9273453);
INSERT INTO `pack_category` VALUES (/*pack_name*/"k3ubkw", /*category*/7, /*file_size*/744160);
INSERT INTO `pack_category` VALUES (/*pack_name*/"zze1oz", /*category*/6, /*file_size*/5014623);
INSERT INTO `pack_category` VALUES (/*pack_name*/"zze1oz", /*category*/7, /*file_size*/5437984);
INSERT INTO `pack_category` VALUES (/*pack_name*/"8s9zr1", /*category*/6, /*file_size*/5094132);
INSERT INTO `pack_category` VALUES (/*pack_name*/"8s9zr1", /*category*/7, /*file_size*/2030560);
INSERT INTO `pack_category` VALUES (/*pack_name*/"jeqdvo", /*category*/6, /*file_size*/1546137);
INSERT INTO `pack_category` VALUES (/*pack_name*/"jeqdvo", /*category*/7, /*file_size*/8891488);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qtifd5", /*category*/6, /*file_size*/9622944);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qtifd5", /*category*/7, /*file_size*/859840);
INSERT INTO `pack_category` VALUES (/*pack_name*/"0d76rp", /*category*/6, /*file_size*/9155029);
INSERT INTO `pack_category` VALUES (/*pack_name*/"0d76rp", /*category*/7, /*file_size*/733632);
INSERT INTO `pack_category` VALUES (/*pack_name*/"vtqezq", /*category*/6, /*file_size*/9682165);
INSERT INTO `pack_category` VALUES (/*pack_name*/"vtqezq", /*category*/7, /*file_size*/767040);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ati51l", /*category*/6, /*file_size*/9439471);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ati51l", /*category*/7, /*file_size*/720320);
INSERT INTO `pack_category` VALUES (/*pack_name*/"p3p9az", /*category*/6, /*file_size*/3348671);
INSERT INTO `pack_category` VALUES (/*pack_name*/"p3p9az", /*category*/7, /*file_size*/7133824);
INSERT INTO `pack_category` VALUES (/*pack_name*/"hw51yn", /*category*/6, /*file_size*/3872571);
INSERT INTO `pack_category` VALUES (/*pack_name*/"hw51yn", /*category*/7, /*file_size*/6555104);
INSERT INTO `pack_category` VALUES (/*pack_name*/"v5przx", /*category*/6, /*file_size*/7146948);
INSERT INTO `pack_category` VALUES (/*pack_name*/"v5przx", /*category*/7, /*file_size*/3274272);
INSERT INTO `pack_category` VALUES (/*pack_name*/"dfe02x", /*category*/6, /*file_size*/9710984);
INSERT INTO `pack_category` VALUES (/*pack_name*/"dfe02x", /*category*/7, /*file_size*/728896);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6qv4f8", /*category*/6, /*file_size*/9784477);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6qv4f8", /*category*/7, /*file_size*/686624);
INSERT INTO `pack_category` VALUES (/*pack_name*/"l0ptps", /*category*/6, /*file_size*/8070300);
INSERT INTO `pack_category` VALUES (/*pack_name*/"l0ptps", /*category*/7, /*file_size*/2048640);
INSERT INTO `pack_category` VALUES (/*pack_name*/"3lkg9h", /*category*/6, /*file_size*/9641758);
INSERT INTO `pack_category` VALUES (/*pack_name*/"3lkg9h", /*category*/7, /*file_size*/838784);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qu77o7", /*category*/6, /*file_size*/9776724);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qu77o7", /*category*/7, /*file_size*/673984);
INSERT INTO `pack_category` VALUES (/*pack_name*/"wgf4a6", /*category*/6, /*file_size*/9746329);
INSERT INTO `pack_category` VALUES (/*pack_name*/"wgf4a6", /*category*/7, /*file_size*/706304);
INSERT INTO `pack_category` VALUES (/*pack_name*/"rzv4rt", /*category*/6, /*file_size*/9733481);
INSERT INTO `pack_category` VALUES (/*pack_name*/"rzv4rt", /*category*/7, /*file_size*/635968);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ffgwp4", /*category*/6, /*file_size*/7670442);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ffgwp4", /*category*/7, /*file_size*/862464);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ja8zau", /*category*/6, /*file_size*/6082250);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ja8zau", /*category*/7, /*file_size*/3942144);
INSERT INTO `pack_category` VALUES (/*pack_name*/"cznkwr", /*category*/6, /*file_size*/9573161);
INSERT INTO `pack_category` VALUES (/*pack_name*/"cznkwr", /*category*/7, /*file_size*/911680);
INSERT INTO `pack_category` VALUES (/*pack_name*/"kzynkc", /*category*/6, /*file_size*/8760648);
INSERT INTO `pack_category` VALUES (/*pack_name*/"kzynkc", /*category*/7, /*file_size*/1625056);
