CREATE TABLE pack_category(
  pack_name TEXT NOT NULL,
  category INTEGER NOT NULL,
  file_size INTEGER NOT NULL,
  PRIMARY KEY (pack_name, category)
);
INSERT INTO `pack_category` VALUES (/*pack_name*/"8cy3fw", /*category*/6, /*file_size*/1565089);
INSERT INTO `pack_category` VALUES (/*pack_name*/"8cy3fw", /*category*/7, /*file_size*/8891488);
INSERT INTO `pack_category` VALUES (/*pack_name*/"nr854l", /*category*/6, /*file_size*/9776610);
INSERT INTO `pack_category` VALUES (/*pack_name*/"nr854l", /*category*/7, /*file_size*/686624);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ly34wx", /*category*/6, /*file_size*/8855082);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ly34wx", /*category*/7, /*file_size*/1625056);
INSERT INTO `pack_category` VALUES (/*pack_name*/"3i8b6m", /*category*/6, /*file_size*/9534122);
INSERT INTO `pack_category` VALUES (/*pack_name*/"3i8b6m", /*category*/7, /*file_size*/859840);
INSERT INTO `pack_category` VALUES (/*pack_name*/"eoj5jm", /*category*/6, /*file_size*/9168149);
INSERT INTO `pack_category` VALUES (/*pack_name*/"eoj5jm", /*category*/7, /*file_size*/733632);
INSERT INTO `pack_category` VALUES (/*pack_name*/"j4lyy7", /*category*/6, /*file_size*/5008191);
INSERT INTO `pack_category` VALUES (/*pack_name*/"j4lyy7", /*category*/7, /*file_size*/5437984);
INSERT INTO `pack_category` VALUES (/*pack_name*/"rb4ihr", /*category*/6, /*file_size*/9718051);
INSERT INTO `pack_category` VALUES (/*pack_name*/"rb4ihr", /*category*/7, /*file_size*/706304);
INSERT INTO `pack_category` VALUES (/*pack_name*/"lcmxyk", /*category*/6, /*file_size*/9422000);
INSERT INTO `pack_category` VALUES (/*pack_name*/"lcmxyk", /*category*/7, /*file_size*/625824);
INSERT INTO `pack_category` VALUES (/*pack_name*/"0zoxsc", /*category*/6, /*file_size*/8464402);
INSERT INTO `pack_category` VALUES (/*pack_name*/"0zoxsc", /*category*/7, /*file_size*/690432);
INSERT INTO `pack_category` VALUES (/*pack_name*/"aoiz91", /*category*/6, /*file_size*/2070585);
INSERT INTO `pack_category` VALUES (/*pack_name*/"aoiz91", /*category*/7, /*file_size*/673984);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7vovu2", /*category*/6, /*file_size*/7159574);
INSERT INTO `pack_category` VALUES (/*pack_name*/"7vovu2", /*category*/7, /*file_size*/3311200);
INSERT INTO `pack_category` VALUES (/*pack_name*/"asy62k", /*category*/6, /*file_size*/8600079);
INSERT INTO `pack_category` VALUES (/*pack_name*/"asy62k", /*category*/7, /*file_size*/862464);
INSERT INTO `pack_category` VALUES (/*pack_name*/"wvm7p9", /*category*/6, /*file_size*/9569628);
INSERT INTO `pack_category` VALUES (/*pack_name*/"wvm7p9", /*category*/7, /*file_size*/911680);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2u2nzp", /*category*/6, /*file_size*/6132437);
INSERT INTO `pack_category` VALUES (/*pack_name*/"2u2nzp", /*category*/7, /*file_size*/2030560);
INSERT INTO `pack_category` VALUES (/*pack_name*/"top3sj", /*category*/6, /*file_size*/9166478);
INSERT INTO `pack_category` VALUES (/*pack_name*/"top3sj", /*category*/7, /*file_size*/767040);
INSERT INTO `pack_category` VALUES (/*pack_name*/"c7im3z", /*category*/6, /*file_size*/9148651);
INSERT INTO `pack_category` VALUES (/*pack_name*/"c7im3z", /*category*/7, /*file_size*/811616);
INSERT INTO `pack_category` VALUES (/*pack_name*/"bxzd48", /*category*/6, /*file_size*/9657500);
INSERT INTO `pack_category` VALUES (/*pack_name*/"bxzd48", /*category*/7, /*file_size*/827744);
INSERT INTO `pack_category` VALUES (/*pack_name*/"cseb8b", /*category*/6, /*file_size*/9501516);
INSERT INTO `pack_category` VALUES (/*pack_name*/"cseb8b", /*category*/7, /*file_size*/957216);
INSERT INTO `pack_category` VALUES (/*pack_name*/"d28jik", /*category*/6, /*file_size*/9734479);
INSERT INTO `pack_category` VALUES (/*pack_name*/"d28jik", /*category*/7, /*file_size*/744160);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qa4gbw", /*category*/6, /*file_size*/9754372);
INSERT INTO `pack_category` VALUES (/*pack_name*/"qa4gbw", /*category*/7, /*file_size*/728896);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ltir64", /*category*/6, /*file_size*/9846920);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ltir64", /*category*/7, /*file_size*/635968);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6onq24", /*category*/6, /*file_size*/3176022);
INSERT INTO `pack_category` VALUES (/*pack_name*/"6onq24", /*category*/7, /*file_size*/7274336);
INSERT INTO `pack_category` VALUES (/*pack_name*/"muf6br", /*category*/6, /*file_size*/8753915);
INSERT INTO `pack_category` VALUES (/*pack_name*/"muf6br", /*category*/7, /*file_size*/1559104);
INSERT INTO `pack_category` VALUES (/*pack_name*/"3pvnpo", /*category*/6, /*file_size*/4865341);
INSERT INTO `pack_category` VALUES (/*pack_name*/"3pvnpo", /*category*/7, /*file_size*/5072608);
INSERT INTO `pack_category` VALUES (/*pack_name*/"we11cw", /*category*/6, /*file_size*/8358680);
INSERT INTO `pack_category` VALUES (/*pack_name*/"we11cw", /*category*/7, /*file_size*/1784192);
INSERT INTO `pack_category` VALUES (/*pack_name*/"p3p9az", /*category*/6, /*file_size*/3348671);
INSERT INTO `pack_category` VALUES (/*pack_name*/"p3p9az", /*category*/7, /*file_size*/7133824);
INSERT INTO `pack_category` VALUES (/*pack_name*/"u5pohh", /*category*/6, /*file_size*/6877563);
INSERT INTO `pack_category` VALUES (/*pack_name*/"u5pohh", /*category*/7, /*file_size*/3274272);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ja8zau", /*category*/6, /*file_size*/6082250);
INSERT INTO `pack_category` VALUES (/*pack_name*/"ja8zau", /*category*/7, /*file_size*/3942144);
INSERT INTO `pack_category` VALUES (/*pack_name*/"zq9ion", /*category*/6, /*file_size*/8391938);
INSERT INTO `pack_category` VALUES (/*pack_name*/"zq9ion", /*category*/7, /*file_size*/2048640);
